version: '3'

services:
  

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: victor
      MONGO_INITDB_ROOT_PASSWORD: 33333386
    ports:
      - "33033:33033"
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge